# Generated by Django 4.2.10 on 2026-05-20 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Material title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Material description')),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('document', 'Document'), ('image', 'Image'), ('link', 'Link'), ('other', 'Other')], help_text='Type of material', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Material file', null=True, upload_to='course_materials/')),
                ('external_link', models.URLField(blank=True, help_text='External link to material')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_published', models.BooleanField(default=True, help_text='Whether material is visible to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course associated with material', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
            ],
            options={
                'verbose_name': 'Study Material',
                'verbose_name_plural': 'Study Materials',
                'ordering': ['course', 'order', '-created_at'],
            },
        ),
    ]
