# Generated by Django 4.2.10 on 2026-05-20 01:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Course title', max_length=255)),
                ('code', models.CharField(help_text='Course code/identifier', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Course description')),
                ('thumbnail', models.ImageField(blank=True, help_text='Course thumbnail image', null=True, upload_to='course_thumbnails/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Course status', max_length=20)),
                ('credits', models.IntegerField(default=3, help_text='Course credits', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('max_students', models.IntegerField(help_text='Maximum number of students', validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity', models.IntegerField(default=0, help_text='Current student count')),
                ('start_date', models.DateField(help_text='Course start date')),
                ('end_date', models.DateField(help_text='Course end date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether course is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', help_text='Enrollment status', max_length=20)),
                ('enrolled_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, help_text='Date when course was completed', null=True)),
                ('course', models.ForeignKey(help_text='Enrolled course', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrolled_date'],
            },
        ),
    ]
