# Generated by Django 4.2.10 on 2026-05-20 01:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Assignment title', max_length=255)),
                ('description', models.TextField(help_text='Assignment description and instructions')),
                ('instructions', models.TextField(blank=True, help_text='Detailed instructions')),
                ('due_date', models.DateTimeField(help_text='Assignment due date')),
                ('total_marks', models.IntegerField(default=100, help_text='Total marks for assignment', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('passing_marks', models.IntegerField(default=40, help_text='Passing marks for assignment', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(help_text='Submitted file', upload_to='assignments/')),
                ('submission_text', models.TextField(blank=True, help_text='Submission text content')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Late Submission')], default='submitted', help_text='Submission status', max_length=20)),
                ('marks_obtained', models.IntegerField(blank=True, help_text='Marks obtained', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True, help_text='Teacher feedback')),
                ('graded_date', models.DateTimeField(blank=True, help_text='Date of grading', null=True)),
                ('assignment', models.ForeignKey(help_text='Assignment submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'ordering': ['-submission_date'],
            },
        ),
    ]
