# Generated by Django 4.2.10 on 2026-05-20 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Announcement title', max_length=255)),
                ('content', models.TextField(help_text='Announcement content')),
                ('attachment', models.FileField(blank=True, help_text='Announcement attachment', null=True, upload_to='announcements/')),
                ('is_important', models.BooleanField(default=False, help_text='Mark as important announcement')),
                ('is_published', models.BooleanField(default=True, help_text='Whether announcement is visible to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-is_important', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(help_text='Announcement read', on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='announcements.announcement')),
            ],
            options={
                'verbose_name': 'Announcement Read',
                'verbose_name_plural': 'Announcements Read',
            },
        ),
    ]
