# Generated by Django 4.2.10 on 2026-05-20 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementread',
            name='student',
            field=models.ForeignKey(help_text='Student who read', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='announcements_read', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(help_text='Course for which announcement is posted', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.course'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='posted_by',
            field=models.ForeignKey(help_text='User who posted announcement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['announcement'], name='announcemen_announc_cd358e_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['student'], name='announcemen_student_69ced1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementread',
            unique_together={('announcement', 'student')},
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['course'], name='announcemen_course__d235c3_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_published'], name='announcemen_is_publ_44200e_idx'),
        ),
    ]
