# Generated by Django 4.2.10 on 2026-05-20 01:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, help_text='Answer text for short/long answer questions')),
                ('is_correct', models.BooleanField(help_text='Whether answer is correct', null=True)),
                ('marks_obtained', models.IntegerField(blank=True, help_text='Marks obtained for this answer', null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(help_text='Option text')),
                ('is_correct', models.BooleanField(default=False, help_text='Is this the correct option')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Question text')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('true_false', 'True/False')], help_text='Type of question', max_length=20)),
                ('marks', models.IntegerField(default=1, help_text='Marks for this question', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Quiz title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Quiz description')),
                ('total_questions', models.IntegerField(help_text='Total number of questions', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_marks', models.IntegerField(default=100, help_text='Total marks for quiz', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('passing_marks', models.IntegerField(default=40, help_text='Passing marks for quiz', validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_minutes', models.IntegerField(default=30, help_text='Quiz duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateTimeField(help_text='Quiz start date and time')),
                ('end_date', models.DateTimeField(help_text='Quiz end date and time')),
                ('is_published', models.BooleanField(default=False, help_text='Whether quiz is published')),
                ('show_answers', models.BooleanField(default=False, help_text='Show correct answers to students after submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Time when student submitted quiz', null=True)),
                ('marks_obtained', models.IntegerField(blank=True, help_text='Marks obtained', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_submitted', models.BooleanField(default=False, help_text='Whether quiz is submitted')),
                ('quiz', models.ForeignKey(help_text='Quiz submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quizzes.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Submission',
                'verbose_name_plural': 'Quiz Submissions',
                'ordering': ['-start_time'],
            },
        ),
    ]
