# Generated by Django 4.2.10 on 2026-05-20 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Attendance date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='absent', help_text='Attendance status', max_length=20)),
                ('time_marked', models.TimeField(blank=True, help_text='Time when student marked present/late', null=True)),
                ('late_message', models.TextField(blank=True, help_text='Student message explaining late arrival')),
                ('late_photo', models.ImageField(blank=True, help_text='Photo proof for late arrival', null=True, upload_to='late_arrivals/')),
                ('marked_automatically', models.BooleanField(default=False, help_text='Whether status was automatically marked as absent')),
                ('approval_remarks', models.TextField(blank=True, help_text='Teacher remarks on late arrival approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'student'],
            },
        ),
    ]
